# Generated by Django 3.0.5 on 2024-04-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20210213_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='lastDonated',
            field=models.CharField(default='1 week ago', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='lastDonated',
            field=models.CharField(default='test1', max_length=30),
            preserve_default=False,
        ),
    ]
